version: "3"
services:
  app:
    container_name: "app"
    image: local/app:latest
    restart: unless-stopped
    expose:
      - 3000
    depends_on:
      - database
    ports:
      - 3000:3000

  database:
      container_name: postgres
      image: postgres
      restart: unless-stopped
      expose:
        - 5432
      env_file:
        - db.env
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: